use majorAdvisor

db.students.insert([
    {name:"Abigail Mathis", year:2022, id:"996844789", onhold:false, classes:["MTH 111 Calculus 1", "CSC 102 How the Internet Works", "CSC 105 Interactive Web Documents"], advisor:"Jordan Crouser"},
    {name:"Julia Clarkson", year:2022, id:"993208605", onhold:false, classes: ["MTH 111 Calculus 1", "MTH 153 Discrete Math", "CSC 111 Intro Computer Science through Programming"], advisor:"Dominique F. Thiébaut"},
    {name:"Penelope North", year:2021, id:"992250735", onhold:true, classes:["MTH 111 Calculus 1", "CSC 111 Intro Computer Science through Programming", "CSC 212 Programming with Data Structures"], advisor:"Jordan Crouser"},
    {name:"Joan Buckland", year:2021, id:"997223695", onhold:false, classes:["MTH 112 Calculus 2", "CSC 111 Intro Computer Science through Programming", "CSC 212 Programming with Data Structures", "CSC 231 Microprocessors and Assembly", "CSC 252 Algorithms"], advisor:"Dominique F. Thiébaut"},
    {name:"Caroline Oliver", year:2021, id:"991238922", onhold:false, classes:["MTH 112 Calculus 2", "MTH 153 Discrete Math", "CSC 103 How Computers Work", "CSC 105 Interactive Web Documents"], advisor:"Jordan Crouser"},
    {name:"Maria Nolan", year:2021, id:"990609692", onhold:false, classes:["MTH 111 Calculus 1", "MTH 153 Discrete Math", "CSC 111 Intro Computer Science through Programming", "CSC 212 Programming with Data Structures", "CSC 252 Algorithms", "CSC 290 Artificial Intelligence"], advisor:"Dominique F. Thiébaut"},
    {name:"Rachel Dickens", year:2021, id:"997227020", onhold:false, classes:["MTH 111 Calculus 1", "CSC 111 Intro Computer Science through Programming"], advisor:"Jordan Crouser"},
    {name:"Michelle Langdon", year:2020, id:"992923879", onhold:false, classes:["MTH 112 Calculus 2", "CSC 111 Intro Computer Science through Programming", "CSC 212 Programming with Data Structures", "CSC 252 Algorithms", "CSC 290 Artificial Intelligence"], advisor:"Dominique F. Thiébaut"},
    {name:"Katherine Piper", year:2020, id:"994302090", onhold:false, classes:["MTH 111 Calculus 1", "MTH 153 Discrete Math", "CSC 111 Intro Computer Science through Programming", "CSC 212 Programming with Data Structures", "CSC 252 Algorithms", "CSC 256 Intelligent User Interfaces"], advisor:"Jordan Crouser"},
    {name:"Penelope Stewart", year:2020, id:"996147771", onhold:false, classes:["MTH 111 Calculus 1", "MTH 153 Discrete Math", "CSC 103 How Computers Work", "CSC 105 Interactive Web Documents"], advisor:"Dominique F. Thiébaut"},
    {name:"Lillian Martin", year:2020, id:"993906156", onhold:true, classes:["MTH 112 Calculus 2", "CSC 111 Intro Computer Science through Programming", "CSC 212 Programming with Data Structures", "CSC 231 Microprocessors and Assembly", "CSC 252 Algorithms", "CSC 256 Intelligent User Interfaces", "CSC 290 Artificial Intelligence"], advisor:"Jordan Crouser"},
    {name:"Emily Carr", year:2020, id:"997932275", onhold:false, classes:["MTH 111 Calculus 1", "MTH 153 Discrete Math", "CSC 111 Intro Computer Science through Programming", "CSC 212 Programming with Data Structures", "CSC 231 Microprocessors and Assembly", "CSC 252 Algorithms", "CSC 270 Digital Circuits and Systems"], advisor:"Dominique F. Thiébaut"},
    {name:"Rachel Greene", year:2019, id:"998104178", onhold:false, classes:["MTH 112 Calculus 2", "MTH 153 Discrete Math", "CSC 111 Intro Computer Science through Programming", "CSC 212 Programming with Data Structures", "CSC 231 Microprocessors and Assembly", "CSC 270 Digital Circuits and Systems"], advisor:"Jordan Crouser"},
    {name:"Stephanie Duncan", year:2019, id:"993459290", onhold:false, classes:["MTH 111 Calculus 1", "MTH 153 Discrete Math", "CSC 111 Intro Computer Science through Programming", "CSC 212 Programming with Data Structures", "CSC 231 Microprocessors and Assembly", "CSC 252 Algorithms", "CSC 256 Intelligent User Interfaces", "CSC 290 Artificial Intelligence"], advisor:"Dominique F. Thiébaut"},
    {name:"Diane Morgan", year:2019, id:"996571054", onhold:false, classes:["MTH 112 Calculus 2", "MTH 153 Discrete Math", "CSC 103 How Computers Work","CSC 105 Interactive Web Documents", "CSC 212 Programming with Data Structures", "CSC 231 Microprocessors and Assembly", "CSC 252 Algorithms"], advisor:"Jordan Crouser"},
    {name:"Kimberly Vance", year:2019, id:"991041195", onhold:false, classes:["MTH 111 Calculus 1", "MTH 153 Discrete Math", "CSC 111 Intro Computer Science through Programming" ,"CSC 212 Programming with Data Structures", "CSC 250 Theoretical Foundations Computer Science", "CSC 252 Algorithms", "CSC 256 Intelligent User Interfaces"], advisor:"Dominique F. Thiébaut"},
    {name:"Jennifer Kelly", year:2019, id:"994943302", onhold:false, classes:["MTH 111 Calculus 1", "CSC 111 Intro Computer Science through Programming" ,"CSC 212 Programming with Data Structures", "CSC 231 Microprocessors and Assembly", "CSC 250 Theoretical Foundations Computer Science", "CSC 252 Algorithms", "CSC 256 Intelligent User Interfaces", "CSC 290 Artificial Intelligence", "CSC354 Seminar in Music Processing"], advisor:"Jordan Crouser"},
    {name:"Jasmine Mackay", year:2019, id:"996818706", onhold:false, classes:["MTH 111 Calculus 1", "MTH 153 Discrete Math", "CSC 111 Intro Computer Science through Programming", "CSC 212 Programming with Data Structures", "CSC 231 Microprocessors and Assembly", "CSC 252 Algorithms", "CSC 256 Intelligent User Interfaces", "CSC 270 Digital Circuits and Systems"], advisor:"Dominique F. Thiébaut"},
    {name:"Virginia Avery", year:2019, id:"997085007", onhold:false, classes:["MTH 112 Calculus 2", "MTH 153 Discrete Math", "CSC 111 Intro Computer Science through Programming", "CSC 212 Programming with Data Structures", "CSC 231 Microprocessors and Assembly", "CSC 250 Theoretical Foundations Computer Science", "CSC 252 Algorithms", "CSC 270 Digital Circuits and Systems", "CSC 290 Artificial Intelligence", "CSC 354 Seminar in Music Processing"], advisor:"Jordan Crouser"},
    {name:"Diane Hart", year:2019, id:"999526301", onhold:true, classes:["MTH 112 Calculus 2", "MTH 153 Discrete Math", "CSC 111 Intro Computer Science through Programming", "CSC 212 Programming with Data Structures", "CSC 231 Microprocessors and Assembly", "CSC 250 Theoretical Foundations Computer Science", "CSC 252 Algorithms", "CSC 256 Intelligent User Interfaces", "CSC 270 Digital Circuits and Systems", "CSC 290 Artificial Intelligence", "CSC 330 Database Systems"], advisor:"Dominique F. Thiébaut"},
]);
// db.classes.insert([
//     {name:"CSC102 How the Internet Works", number: "CSC102", Theory:false, Programming:false, Systems:true},
//     {name:"CSC103 How Computers Work", number: "CSC103", Theory:false, Programming:false, Systems:true},
//     {name:"CSC105 Interactive Web Documents", number: "CSC105", Theory:false, Programming:true, Systems:false},
//     {name:"CSC109 Communicating with Data", number: "CSC109", Theory:false, Programming:false, Systems:false},
//     {name:"CSC111 Intro Computer Science through Programming", number: "CSC111", Theory:false, Programming:true, Systems:false},
//     {name:"CSC212 Programming with Data Structures", number: "CSC212", Theory:false, Programming:true, Systems:false},
//     {name:"CSC220 Advanced Programming Techniques", number: "CSC220", Theory:false, Programming:true, Systems:false},
//     {name:"CSC231 Microprocessors and Assembly", number: "CSC231", Theory:false, Programming:true, Systems:true},
//     {name:"CSC250 Theoretical Foundations Computer Science", number: "CSC250", Theory:true, Programming:false, Systems:false},
//     {name:"CSC252 Algorithms", Theory:true, number: "CSC252", Programming:false, Systems:false},
//     {name:"CSC256 Intelligent User Interfaces", number: "CSC256", Theory:false, Programming:true, Systems:false},
//     {name:"CSC262 Operating Systems", number: "CSC262", Theory:false, Programming:true, Systems:true},
//     {name:"CSC270 Digital Circuits and Systems", number: "CSC270", Theory:false, Programming:false, Systems:true},
//     {name:"CSC290 Artificial Intelligence", number: "CSC290", Theory:true, Programming:true, Systems:false},
//     {name:"CSC293 Machine Learning", number: "CSC293", Theory:true, Programming:true, Systems:false},
//     {name:"CSC330 Database Systems", number: "CSC330", Theory:false, Programming:true, Systems:true},
//     {name:"CSC334 Topics in Computational Biology", number: "CSC334", Theory:true, Programming:true, Systems:false},
//     {name:"CSC354 Seminar in Music Processing", number: "CSC354", Theory:true, Programming:true, Systems:false},
//     {name:"CSC390 Seminar in Artificial Intelligence", number: "CSC390", Theory:true, Programming:false, Systems:false},
// ]);
